<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.MongoDB" Version="13.1.0" />
    <PackageReference Include="Colombo.ResultPattern" Version="8.0.0" />
    <PackageReference Include="WolverineFx" Version="5.9.2" />
    <PackageReference Include="WolverineFx.FluentValidation" Version="5.9.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\Abstractions\" />
    <Folder Include="Data\Abstractions\Wolwerine\" />
    <Folder Include="Data\Policy\Commands\Delete\" />
    <Folder Include="Data\Policy\Commands\Update\" />
    <Folder Include="Data\Policy\Queries\GetById\" />
    <Folder Include="Entities\Queue\Mongo\History\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Aspire\Shared\Shared.csproj" />
  </ItemGroup>

</Project>
