services:
  gateway:
    image: gateway:dev 
    container_name: gateway-dev
    hostname: gateway-dev
    ports:
      - "7111:7111"
    environment:
      ASPNETCORE_HTTP_PORTS: "7111"
      ASPNETCORE_ENVIRONMENT: "Development"
      OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
      OTEL_EXPORTER_OTLP_ENDPOINT: "https://otlp-gateway-prod-sa-east-1.grafana.net/otlp"
      OTEL_EXPORTER_OTLP_HEADERS: "Authorization=Basic MTQxMjg0MjpnbGNfZXlKdklqb2lNVFUyTnpFeE5pSXNJbTRpT2lKemRHRmpheTB4TkRFeU9EUXlMVzkwYkhBdGQzSnBkR1V0WjJGMFpYZGhlU0lzSW1zaU9pSnhkamhHVGprM09UaE9PRE5oTTJSeVltVkpjelZKWXpFaUxDSnRJanA3SW5JaU9pSndjbTlrTFhOaExXVmhjM1F0TVNKOWZRPT0="

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: gateway
      MONGODB_INITDB_ROOT_PASSWORD: g4t3w4y
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
