POST https://localhost:7111/INTR
Content-Type: text/xml; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzdG9jazM2MCIsImp0aSI6IjA1MmZmZjg0LTc1NWUtNDY0Ny1hOTAzLWIwZTU5MWE5MjY2YiIsImV4cCI6MTc2MzE1MTI0MCwiaXNzIjoib2xvcmluLWdhdGV3YXkifQ.1Kv2BIawbhGtVrYFMFyxQNIp9J-yqIeREwom3hbR-Os

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">
   <soapenv:Header/>
   <soapenv:Body>
      <tem:ConsultarPropostaCW>
         <tem:pCodFilial>542</tem:pCodFilial>
         <tem:pCodProposta>9878959</tem:pCodProposta>
      </tem:ConsultarPropostaCW>
   </soapenv:Body>
</soapenv:Envelope>