POST https://localhost:7111/integration-crediare
Content-Type: text/xml; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzdG9jazM2MCIsImp0aSI6Ijg0MDY3Mzg2LTFjNGItNGRiYy04OGI0LTg1ODllOTViNGJkNCIsImV4cCI6MTc2NDI2OTY5OSwiaXNzIjoib2xvcmluLWdhdGV3YXkifQ.zl1kxXg5NW_JoT8lZ_pug1Jx3rpcvfAcAvS-DFMo93Y 

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">
   <soapenv:Header/>
   <soapenv:Body>
      <tem:ConsultarPropostaCW>
         <tem:pCodFilial>542</tem:pCodFilial>
         <tem:pCodProposta>9878959</tem:pCodProposta>
      </tem:ConsultarPropostaCW>
   </soapenv:Body>
</soapenv:Envelope>

###
GET https://localhost:7111/INTR?WSDL
Authorization: Basic c3RvY2szNjA6cGFzc3dvcmQ=

###
POST https://localhost:7111/country/ListOfContinentsByName
Content-Type: text/xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <ListOfCountryNamesByName xmlns="https://soap-service-free.mock.beeceptor.com/CountryInfoService"/>
    </soap:Body>
</soap:Envelope>