<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Endpoints\" />
    <Folder Include="Endpoints\Policy\" />
    <Folder Include="Endpoints\Queue\" />
  </ItemGroup>
  
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Colombo.ResultPattern" Version="8.0.1" />
	<PackageReference Include="Colombo.ResultPattern.AspNetCore" Version="8.0.1" />
    <PackageReference Include="WolverineFx" Version="5.9.2" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Extensions\Extensions.csproj" />
    <ProjectReference Include="..\Message.Domain\Messaging.Domain.csproj" />
  </ItemGroup>
</Project>
